### PR TITLE
Added spanish (generic) translations

### PR DESCRIPTION
**Pull request by gusrub**
Hey there, really liked your theme so I installed it on my blog, however there were no spanish translations so I did them. These are _generic_ spanish.

Feel free to include them in following releases of the theme.

### CODE REVIEW

**Comment by BenSibley** [comment]
Thanks so much Gustavo! I'll add them in the next update.

**Comment by gusrub** [comment]
Hey Ben how's it going? 

Just updated the theme to 1.21 and realized the translation is not there yet, any estimate on the ETA? I can always upload the files manually but it'd be easier to just have them bundled on each update :smiley: 

Thanks!

**Comment by BenSibley** [comment]
Hey I'm so sorry about the delay. I thought I'd added them, but it looks like I completely messed up the pull request and got the wrong content. Not even sure how that happened lol.

I'll do a quick update tomorrow morning with proper files included.

**Comment by gusrub** [comment]
No problem, I'll keep an eye on the updates to keep translation maintained 😄

**Comment by BenSibley** [comment]
Version 1.22 should be available in a few minutes with the working translations.

**Pull request closed without merging**
